parameters:
#    application_base.example.class: Application\BaseBundle\Example

services:
#    application_base.example:
#        class: %application_base.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
