services:
    sonata.admin.user:
        class: Application\AdminBundle\Admin\UserAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Users", label: "User" }
        arguments:
            - ~
            - Application\UserBundle\Entity\User
            - ~
        calls:
            - [ setTranslationDomain, [ApplicationAdminBundle]]