parameters:
#    application_admin.example.class: Application\AdminBundle\Example

services:
#    application_admin.example:
#        class: %application_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
